services:
  - type: web
    name: air-quality-prediction
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: NASA_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
